# mod_rpaf-fork configuration. Edit RPAFproxy_ips to match your reverse proxy.
RPAFenable On
RPAFproxy_ips 192.168. 10.0.0.
RPAFheader X-Forwarded-For
RPAFsethostname Off
RPAFsethttps Off
RPAFsetport Off
